### ISSUE TITLE
AsignaturasEstudiantesTab nunca es agregada

### ISSUE THREAD

**Issue by RafaelMoralesV** [exdevutem/mi-utem#10]
# Description
Uso de la clase AsignaturasEstudiantesTab.

Por lo que estoy notando, la lista de estudiantes no se está ocupando- la forma en que se llama normalmente es en AsignaturaScreen, que corresponde al detalle de una asignatura en concreto. Esta solo se agrega cuando la asignatura posee un campo estudiantes no nulo y de más de cero, pero en ninguna de las asignaturas que veo disponibles encuentro alguna que posea esta tab.
Puede ser un problema de la API?

## Edit
Según el comentario de Jorge, esto quedó obsoleto por un cambio en la API. Esto solo sería reimplementado como un nuevo endpoint dentro de la api debido a que la única forma de conseguir esta info es mediante Scrapping. En caso de que eso se haga, abrá que volver a agregar la pantalla faltante.

## Checklist

- [ ] Reintegrar en la API la lista de estudiantes mediante scrapping.
- [ ] Reintegrar esta pantalla a partir de una nueva llamada a la API, independiente de las que se hace para la asignatura.

## Tipo de cambio

- Corrección de error.

# Resources

![image](https://user-images.githubusercontent.com/42483328/174215486-a5d772f6-a2a1-462c-9ab2-e595fe70e823.png)
Asignatura de ejemplo, no existe un tab de estudiantes.

![image](https://user-images.githubusercontent.com/42483328/174215570-b442298b-ad66-455c-98ac-b4613f235b90.png)
Bloque de código donde esta tab debería ser agregada.

**Comment by mapacheverdugo** [comment]
Efectivamente, se sacó por la refactorización "reciente" de la API. Al ocupar la API del sistema SIGA que nos pasó SISEI, perdimos cierta información, y una de ellas es la lista de estudiantes de cada asignatura. 

Creo que se podría revivir esa información haciendo scrapping desde el backend, de hecho es probable que el código esté ahí, pero habría que implementarlo en la app como una consulta aparte (porque todo lo que es con scrapping se demora como 20 segs x request)

**Comment by RafaelMoralesV** [comment]
Okas
Voy a editar el issue y dejarlo abierto para que se reintegre esto a la app a futuro

**Comment by RafaelMoralesV** [comment]
como que pasó un año de esta wea

**Comment by Im-Fran** [comment]
xD yo veré si se puede hacer algo, esto está disponible para usuarios normales? Digo porque ultimamente he modificado el repo https://github.com/exdevutem/api-mi-utem pero solo con mi acceso de mortal :rofl:

**Comment by Im-Fran** [comment]
ya lo encontré, buscaré el endpoint antiguo y lo agregaré nuevamente a la API

**Comment by Im-Fran** [comment]
Veo que solo se puede obtener la lista utilizando la pagina https://mi.utem.cl (la cual tarda al menos 10 segundos en cargar), así que yo creo que agregaré un endpoint extra para obtener los estudiantes, así no demorar la carga de notas y otros datos

**Comment by RafaelMoralesV** [comment]
@Im-Fran tas como bala mi rey, imparable

quizás habría que considerar un método de caching para ese endpoint, no sé si a nivel de API o de cliente. Por otro lado, quizás el esfuerzo sea desperdiciado si esa función se usa muy poco.

En lo pronto supongo que mientras funcione y muestre, basta y sobre, y luego podemos pensar en optimizar

**Comment by Im-Fran** [comment]
oh wait, ya hay una implementación en el backend, solo que sin uso xD y ya retorna a los estudiantes, veré cuanto tarda y si se puede agregar.

**Comment by Im-Fran** [comment]
Lo malo es que de por si el server de mi utem tarda 6 segundos en cargar el documento en sí, los otros 2/3 segundos son para la verificación de las token. Uno de los cambios que agregué es para reducir el tiempo de carga

**Comment by Im-Fran** [comment]
ahora mismo en mis pruebas tarda hasta 9 segundos, si logro eliminar el uso de la pagina mi.utem.cl al inciar sesión quizá pueda reducir la carga a 3 segundos, e incluso utilizar solo scrapping :stuck_out_tongue:

**Comment by Im-Fran** [comment]
Ok, crearé la PR en unos segundos, fue realmente simple el agregar el endpoint xD
