### ISSUE TITLE
Cambiar el UX/UI del horario

### ISSUE THREAD

**Issue by mapacheverdugo** [exdevutem/mi-utem#18]
La idea es que el horario siga el nuevo diseño del Figma y que además tenga las siguientes funcionalidades
- En los header row y columns se pondrá en negrita el día y bloque actual según hora del dispositivo
- Al entrar el horario es scroll estará centrado en el día y bloque actual según hora del dispositivo
- Existirá una línea indicadora que marcara el progreso del día según hora del dispositivo
- El diseño ahora es simétrico y proporcional a los minutos para que todo funcione

**Comment by RafaelMoralesV** [comment]
quizas sea buena idea agregar un boton que te devuelva al punto inicial también
