### ISSUE TITLE
[BUG] Problemas para mantener sesión

### ISSUE THREAD

**Issue by RafaelMoralesV** [exdevutem/mi-utem#34]
# Description

Es super posible que esto sea un problema a nivel de API, pero abro el Issue aquí porque lo pillé en la app y me da paja revisar

La app está teniendo problemas para mantener sesión. Lo que veo que pasa es lo siguiente:
1. Luego de mantener una sesión sin tocar en [mucho] tiempo (No tengo idea cuanto, pero lo noto al abrir la app luego de algunos días).
2. Abro la app, puedo entrar al menú principal pero no tengo carga de las noticias o códigos QR
3. Intento entrar a la sección de notas, pero no logra cargar luego de varios segundos
4. Al devolverme hacia atrás, la app me empuja a la pestaña de log in
5. Al volver a loguearme todo funciona como es esperado.

Mi guess es que la app está teniendo problemas para regenerar la sesión a partir de las credenciales que se dejaron antes. Mi mayor drama es que no estoy seguro de cómo probar esto para arreglarlo yo mismo..

**Comment by Im-Fran** [comment]
Para esto yo creo que se podria utilizar https://pub.dev/packages/fquery, es en una forma super simple un sistema que si haces una solicitud web te guarda en cache los datos, y si ya existe en cache te muestra los datos guardados mientras los actualiza en background. Para evitar demoras en el login (que actualmente tarda como 13.6 segundos) se podría guardar los datos del usuario y luego con las credenciales guardadas realizar la nueva solicitud.

**Comment by mapacheverdugo** [comment]
Este error ya fue solucionado, lo cierro hasta que lo reporten de nuevo
