### ISSUE TITLE
Musica Se Pausa En Login

### ISSUE THREAD

**Issue by Im-Fran** [exdevutem/mi-utem#35]
Esto puede que afecte a casi todos los usuarios que estan escuchando musica y abren la app xD a mi personalmente me pasa, se pausa la musica en el login, y realmente no tiene sonido el video background del login screen.

https://github.com/exdevutem/mi-utem/blob/1076a4fa6f171af2240aa9baa2ad3795c3d6c0b4/lib/screens/login_screen/_background.dart#L20-L24

Ahora mismo estoy jugando con SwiftUI para arreglar esto, y descubrí una api en ios (AVAudioSession) que permite "arreglar" este problema, y flutter tiene una API similar para esto, [VideoPlayerOptions](https://pub.dev/documentation/video_player/latest/video_player/VideoPlayerOptions-class.html) que creo que es lo que se utiliza ahora mismo para el background.

Solo se debe de configurar la opción `mixWithOthers` a `true` y creo que se arregla el escuchar música + estar en el login.

**Comment by Im-Fran** [comment]
Creo que el inicializador debe ser algo así:
```dart
 _controller = VideoPlayerController.asset('assets/videos/login_bg.mp4', videoPlayerOptions: VideoPlayerOptions(mixWithOthers: true)) 
   ..setVolume(0) 
   ..play() 
   ..setLooping(true) 
   ..initialize(); 
```

Esto lo hice con chatgpt y realmente no tengo idea si funciona, pero ahora mismo no puedo probarlo porque tendría que realizar todo el setup de flutter y dart y todo xD

**Comment by Im-Fran** [comment]
Cerraré esto porque el arreglo ya fué implementado.

**Comment by mapacheverdugo** [comment]
Pero y te funciona ahora? @Im-Fran

**Comment by Im-Fran** [comment]
sip
